### ISSUE TITLE
Need for a class service:ServiceObject and relating property

### ISSUE THREAD

**Issue by cKlee** [dini-ag-kim/service-ontology#3]
In the Holding Ontology I'm not satisfied with the relation between an Item and a Service. This is because different attributes of the Item are important when it is the object of a Service.

For instance different callnumbers or labels are important for different Services. One could say that the item has different functions or roles.

```
$item ex:hasRole $serviceObject .
$serviceObject a service:ServiceObject .
$serviceObject holding:label "HB 17 Rg 500" .
$serviceObject daia:availableFor $service .
$service a dso:Presentation .
```

A `service:ServiceObject` should be defined as follows:

```
service:ServiceObject a owl:Class ;
    rdfs:label "service object"@en ;
    rdfs:comment "The thing which is the object of a service"@en ;
    rdfs:isDefinedBy <> .
```

A simple example: In the sentence "Peter is lending a car", the 'car' is the object of the service 'loan'.

There may also be a Service-ServiceObject-Relation and  a ServiceObject-Service-Relation like:

```
$service service:includes $serviceObject .
$serviceObject service:includedIn $service .
```

I'm not sure about the property for the Item-ServiceObject-Relation. I haven't found any candidates for this. So possibly take it into Holding Ontology?

```
holding:hasRole a owl:ObjectProperty ;
     rdfs:label "has role"@en ;
     rdfs:comment "Relates a document to its role with respect to an activity."@en .
```

**Comment by cKlee** [comment]
On a second thought `dct:hasPart` may be sufficient for the Item-ServiceOffer-Relation.

```
$item dct:hasPart $serviceObject .
$serviceObject a service:ServiceObject .
$serviceObject holding:label "HB 17 Rg 500" .
$serviceObject daia:availableFor $service .
$service a dso:Presentation .
```

**Comment by nichtich** [comment]
This solves a problem at the wrong place. If different aspects of a service are relevant in different contexts then its task of the application to select its context. RDF is an open world so applications have to deal with it. To reuse your 'car' example: the service could be traveling by car, taking pictures of a car, getting pizza delivered by car... there is no clear semantics in the new class and properties. One could rename it to "relatedResource" but it must not be confused with the Service itself.

**Comment by cKlee** [comment]
Allright, I drop this in favour of discussion about another item - service modelling https://github.com/dini-ag-kim/holding-ontology/issues/30
